version: '3.8'

services:
  notification_service:
    build: .
    container_name: notification_service
    command: gunicorn notification_service.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8008:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=notification_service.settings
      - MYSQL_DATABASE=notification_db
      - MYSQL_HOST=mysql_notification
      - MYSQL_ROOT_PASSWORD=123456

  mysql_notification:
    image: mysql:8.0
    container_name: mysql_notification
    restart: always
    environment:
      MYSQL_DATABASE: notification_db  # Use a separate database for notification service
      MYSQL_ROOT_PASSWORD: 123456
    ports:
     - "3314:3306"  # Changed port to avoid conflict

volumes:
  notification_db_data:
