# Generated by Django 5.2 on 2025-04-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('pharmacist', 'Pharmacist'), ('admin', 'Admin'), ('lab_technician', 'Lab Technician')], max_length=20)),
                ('shift_time', models.CharField(max_length=100)),
            ],
        ),
    ]
