version: '3.8'

services:
  nurse_service:
    build: .
    container_name: nurse_service
    command: gunicorn nurse_service.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8005:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=nurse_service.settings
      - MYSQL_DATABASE=nurse_db
      - MYSQL_HOST=mysql_nurse
      - MYSQL_ROOT_PASSWORD=123456

  mysql_nurse:
    image: mysql:8.0
    container_name: mysql_nurse
    restart: always
    environment:
      MYSQL_DATABASE: nurse_db  # Use a separate database for nurse service
      MYSQL_ROOT_PASSWORD: 123456
    ports:
     - "3311:3306"  # Changed port to avoid conflict

volumes:
  nurse_db_data:
