version: '3.8'

services:
  pharmacy_service:
    build: .
    container_name: pharmacy_service
    command: gunicorn pharmacy_service.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8004:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=pharmacy_service.settings
      - MYSQL_DATABASE=pharmacy_db
      - MYSQL_HOST=mysql_pharmacy
      - MYSQL_ROOT_PASSWORD=123456

  mysql_doctor:
    image: mysql:8.0
    container_name: mysql_pharmacy
    restart: always
    environment:
      MYSQL_DATABASE: pharmacy_db  # Use a separate database for pharmacy service
      MYSQL_ROOT_PASSWORD: 123456
    ports:
     - "3310:3306"  # Changed port to avoid conflict

volumes:
  pharmacy_db_data:
