version: '3.8'

services:
  insurance_service:
    build: .
    container_name: insurance_service
    command: gunicorn insurance_service.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8006:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=insurance_service.settings
      - MYSQL_DATABASE=insurance_db
      - MYSQL_HOST=mysql_insurance
      - MYSQL_ROOT_PASSWORD=123456

  mysql_insurance:
    image: mysql:8.0
    container_name: mysql_insurance
    restart: always
    environment:
      MYSQL_DATABASE: insurance_db  # Use a separate database for insurance service
      MYSQL_ROOT_PASSWORD: 123456
    ports:
     - "3312:3306"  # Changed port to avoid conflict

volumes:
  insurance_db_data:
