# Generated by Django 5.2 on 2025-04-15 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insuranceProvider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('policy_number', models.CharField(max_length=100)),
                ('valid_until', models.DateField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insuranceProvider.insuranceprovider')),
            ],
        ),
    ]
