# Generated by Django 5.2.1 on 2025-05-20 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='type',
            field=models.CharField(choices=[('Outpatient', 'Outpatient'), ('Inpatient', 'Inpatient'), ('Emergency', 'Emergency')], default='Outpatient', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='user_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
