# Generated by Django 5.2 on 2025-04-15 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LabTest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_data', models.TextField()),
                ('file_path', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LabTest.labtest')),
            ],
        ),
    ]
